name: Check TensorFlow Releases

on:
  schedule:
    # Run at 11 PM every day
    - cron: '0 23 * * *'

jobs:
  check-tensorflow-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run the script
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh ./update_releases.sh
